// Generated by scripts/generate-provider-catalog.mjs. Do not edit directly.

import SwiftUI
import UIKit

enum ScooterProvider: String, CaseIterable, Identifiable, Sendable {
    case bolt
    case bird
    case dott
    case hopp
    case lime
    case voi
    case publibike

    var id: String { rawValue }

    var name: String {
        switch self {
        case .bolt: "Bolt"
        case .bird: "Bird"
        case .dott: "Dott"
        case .hopp: "Hopp"
        case .lime: "Lime"
        case .voi: "Voi"
        case .publibike: "PubliBike / Velospot"
        }
    }

    var shortName: String {
        switch self {
        case .bolt: "B"
        case .bird: "Bi"
        case .dott: "D"
        case .hopp: "H"
        case .lime: "L"
        case .voi: "V"
        case .publibike: "PB"
        }
    }

    var color: Color { Color(uiColor: uiColor) }

    var uiColor: UIColor {
        switch self {
        case .bolt: UIColor(red: 0.000000, green: 0.800000, blue: 0.266667, alpha: 1)
        case .bird: UIColor(red: 0.133333, green: 0.133333, blue: 0.133333, alpha: 1)
        case .dott: UIColor(red: 1.000000, green: 0.400000, blue: 0.000000, alpha: 1)
        case .hopp: UIColor(red: 0.000000, green: 0.737255, blue: 0.831373, alpha: 1)
        case .lime: UIColor(red: 0.196078, green: 0.803922, blue: 0.196078, alpha: 1)
        case .voi: UIColor(red: 1.000000, green: 0.078431, blue: 0.576471, alpha: 1)
        case .publibike: UIColor(red: 0.607843, green: 0.349020, blue: 0.713725, alpha: 1)
        }
    }
}
