// This file wraps the generated OpenNext Worker. It is intentionally excluded
// from Next.js type-checking because .open-next/worker.js only exists after the
// application build.
// @ts-expect-error Generated by `opennextjs-cloudflare build`.
import openNextWorker from './.open-next/worker.js';
import { legacyHostRedirect } from './src/lib/legacyHost';

const swissScootersWorker = {
  async fetch(request: Request, env: CloudflareEnv, ctx: ExecutionContext) {
    const redirect = legacyHostRedirect(request);
    return redirect ?? openNextWorker.fetch(request, env, ctx);
  },
};

export default swissScootersWorker;
