// This file wraps the generated OpenNext Worker. It is intentionally excluded
// from Next.js type-checking because .open-next/worker.js only exists after the
// application build.
// The generated module may or may not exist when TypeScript runs, so an
// expectation directive would itself fail after a local OpenNext build.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore -- Generated by `opennextjs-cloudflare build`.
import openNextWorker from './.open-next/worker.js';
import { documentContentSecurityPolicy } from './src/lib/contentSecurityPolicy';
import { legacyHostRedirect } from './src/lib/legacyHost';

function secureDocumentResponse(request: Request, response: Response): Response {
  if (!response.headers.get('Content-Type')?.toLowerCase().startsWith('text/html')) {
    return response;
  }

  const nonce = btoa(crypto.randomUUID());
  const headers = new Headers(response.headers);
  headers.delete('Content-Length');
  headers.set(
    'Content-Security-Policy',
    documentContentSecurityPolicy({
      nonce,
      development: false,
      upgradeInsecureRequests: new URL(request.url).protocol === 'https:',
    }),
  );
  const documentResponse = new Response(response.body, {
    status: response.status,
    statusText: response.statusText,
    headers,
  });
  const nonceHandler = {
    element(element: Element) {
      element.setAttribute('nonce', nonce);
    },
  };

  return new HTMLRewriter()
    .on('script', nonceHandler)
    .on('style', nonceHandler)
    .transform(documentResponse);
}

const swissScootersWorker = {
  async fetch(request: Request, env: CloudflareEnv, ctx: ExecutionContext) {
    const redirect = legacyHostRedirect(request);
    if (redirect) {
      return redirect;
    }

    const response = await openNextWorker.fetch(request, env, ctx);
    return secureDocumentResponse(request, response);
  },
};

export default swissScootersWorker;
