// Generated by scripts/generate-provider-catalog.mjs. Do not edit directly.

import SwiftUI
import UIKit

enum ScooterProvider: String, CaseIterable, Identifiable, Sendable {
    case bolt
    case bird
    case dott
    case hopp
    case lime
    case voi
    case pony
    case publibike

    var id: String { rawValue }

    var name: String {
        switch self {
        case .bolt: "Bolt"
        case .bird: "Bird"
        case .dott: "Dott"
        case .hopp: "Hopp"
        case .lime: "Lime"
        case .voi: "Voi"
        case .pony: "Pony"
        case .publibike: "PubliBike / Velospot"
        }
    }

    var shortName: String {
        switch self {
        case .bolt: "B"
        case .bird: "Bi"
        case .dott: "D"
        case .hopp: "H"
        case .lime: "L"
        case .voi: "V"
        case .pony: "P"
        case .publibike: "PB"
        }
    }

    var color: Color { Color(uiColor: uiColor) }

    var uiColor: UIColor {
        switch self {
        case .bolt: UIColor(red: 0.000000, green: 0.800000, blue: 0.266667, alpha: 1)
        case .bird: UIColor(red: 0.133333, green: 0.133333, blue: 0.133333, alpha: 1)
        case .dott: UIColor(red: 1.000000, green: 0.400000, blue: 0.000000, alpha: 1)
        case .hopp: UIColor(red: 0.000000, green: 0.737255, blue: 0.831373, alpha: 1)
        case .lime: UIColor(red: 0.196078, green: 0.803922, blue: 0.196078, alpha: 1)
        case .voi: UIColor(red: 1.000000, green: 0.078431, blue: 0.576471, alpha: 1)
        case .pony: UIColor(red: 0.000000, green: 0.654902, blue: 0.627451, alpha: 1)
        case .publibike: UIColor(red: 0.607843, green: 0.349020, blue: 0.713725, alpha: 1)
        }
    }
}

enum ScooterProviderCoverage {
    private static let swissAreas: [GeoBounds] = [
        GeoBounds(south: 47.42, west: 7.38, north: 47.7, east: 7.82),
        GeoBounds(south: 46.82, west: 7.2, north: 47.08, east: 7.7),
        GeoBounds(south: 47.03, west: 7.05, north: 47.27, east: 7.45),
        GeoBounds(south: 46.5, west: 6.82, north: 46.7, east: 7.12),
        GeoBounds(south: 47.45, west: 8.72, north: 47.68, east: 9.1),
        GeoBounds(south: 47.08, west: 7.28, north: 47.28, east: 7.52),
        GeoBounds(south: 47.33, west: 8.58, north: 47.55, east: 8.88),
        GeoBounds(south: 47.4, west: 8.47, north: 47.56, east: 8.74),
        GeoBounds(south: 46.1, west: 8.67, north: 46.25, east: 8.9),
        GeoBounds(south: 46.25, west: 6.05, north: 46.55, east: 6.45),
        GeoBounds(south: 47.39, west: 8.47, north: 47.5, east: 8.68),
        GeoBounds(south: 47.45, west: 9.2, north: 47.66, east: 9.58),
        GeoBounds(south: 47.36, west: 9.3, north: 47.58, east: 9.68),
        GeoBounds(south: 47.6, west: 8.42, north: 47.83, east: 8.88),
        GeoBounds(south: 47.28, west: 9.1, north: 47.6, east: 9.65),
        GeoBounds(south: 47.25, west: 8.58, north: 47.43, east: 8.86),
        GeoBounds(south: 47.2, west: 8.68, north: 47.4, east: 8.98),
        GeoBounds(south: 47.38, west: 8.53, north: 47.64, east: 8.97),
        GeoBounds(south: 47.03, west: 8.32, north: 47.31, east: 8.74),
        GeoBounds(south: 47.27, west: 8.34, north: 47.49, east: 8.73),
    ]
    private static let regionalSystems: [(ScooterProvider, GeoBounds)] = [
        (.bird, GeoBounds(south: 41.81, west: 8.53, north: 42.03, east: 8.87)),
        (.bird, GeoBounds(south: 47.46, west: 1.2, north: 47.71, east: 1.44)),
        (.bird, GeoBounds(south: 48.85, west: 4.22, north: 49.07, east: 4.49)),
        (.bird, GeoBounds(south: 47.95, west: -0.94, north: 48.19, east: -0.65)),
        (.bird, GeoBounds(south: 46, west: 3.28, north: 46.27, east: 3.62)),
        (.dott, GeoBounds(south: 44.66, west: -0.86, north: 45.07, east: -0.32)),
        (.dott, GeoBounds(south: 45.49, west: 5.14, north: 45.7, east: 5.39)),
        (.dott, GeoBounds(south: 45.63, west: 4.68, north: 45.92, east: 5)),
        (.dott, GeoBounds(south: 48.73, west: 2.58, north: 48.97, east: 2.86)),
        (.dott, GeoBounds(south: 45.36, west: 6.81, north: 45.56, east: 7)),
        (.dott, GeoBounds(south: 48.73, west: 2.02, north: 48.96, east: 2.24)),
        (.lime, GeoBounds(south: 50.4, west: 2.75, north: 50.9, east: 3.4)),
        (.lime, GeoBounds(south: 43.12, west: 5.22, north: 43.49, east: 5.65)),
        (.pony, GeoBounds(south: 47.33, west: -0.73, north: 47.62, east: -0.38)),
        (.pony, GeoBounds(south: 49.16, west: 1.67, north: 49.75, east: 2.55)),
        (.pony, GeoBounds(south: 44.67, west: -0.86, north: 45.05, east: -0.39)),
        (.pony, GeoBounds(south: 46.96, west: 2.28, north: 47.21, east: 2.53)),
        (.pony, GeoBounds(south: 48.52, west: 2.31, north: 48.73, east: 2.55)),
        (.pony, GeoBounds(south: 48.89, west: -0.76, north: 49.49, east: 0.09)),
        (.pony, GeoBounds(south: 47.59, west: -3.58, north: 47.89, east: -3.21)),
        (.pony, GeoBounds(south: 42.52, west: 2.63, north: 43.03, east: 3.2)),
        (.pony, GeoBounds(south: 46.32, west: -0.09, north: 46.91, east: 0.81)),
        (.voi, GeoBounds(south: 48.77, west: 1.47, north: 49.16, east: 2.3)),
        (.voi, GeoBounds(south: 45.01, west: 5.47, north: 45.37, east: 5.98)),
        (.voi, GeoBounds(south: 49.35, west: -0.05, north: 49.73, east: 0.38)),
        (.voi, GeoBounds(south: 43.11, west: 5.18, north: 43.49, east: 5.65)),
        (.voi, GeoBounds(south: 48.6, west: 1.77, north: 48.95, east: 2.24)),
        (.bolt, GeoBounds(south: 48.8623, west: 8.3074, north: 49.5247, east: 8.7576)),
        (.bolt, GeoBounds(south: 48.4312, west: 9.1335, north: 48.5396, east: 9.2596)),
        (.bolt, GeoBounds(south: 48.4824, west: 9.0088, north: 48.5647, east: 9.1103)),
        (.bolt, GeoBounds(south: 48.6977, west: 9.0717, north: 48.8618, east: 9.2897)),
        (.dott, GeoBounds(south: 50.7249, west: 6.023, north: 50.8211, east: 6.1962)),
        (.dott, GeoBounds(south: 52.4275, west: 13.1051, north: 52.6548, east: 13.6436)),
        (.dott, GeoBounds(south: 51.9238, west: 8.4615, north: 52.0749, east: 8.6393)),
        (.dott, GeoBounds(south: 48.6495, west: 8.959, north: 48.7431, east: 9.0623)),
        (.dott, GeoBounds(south: 51.4257, west: 7.1003, north: 51.5133, east: 7.2923)),
        (.dott, GeoBounds(south: 50.6349, west: 7.0115, north: 50.7878, east: 7.2157)),
        (.dott, GeoBounds(south: 53.0332, west: 8.5819, north: 53.2113, east: 8.9083)),
        (.dott, GeoBounds(south: 53.4718, west: 8.544, north: 53.6408, east: 8.6612)),
        (.dott, GeoBounds(south: 50.7834, west: 6.8557, north: 50.8626, east: 6.9434)),
        (.dott, GeoBounds(south: 52.1916, west: 10.4482, north: 52.339, east: 10.6171)),
        (.dott, GeoBounds(south: 52.5657, west: 9.9847, north: 52.6612, east: 10.1369)),
        (.dott, GeoBounds(south: 50.7751, west: 12.855, north: 50.8757, east: 12.988)),
        (.dott, GeoBounds(south: 50.8217, west: 6.796, north: 51.0145, east: 7.1351)),
        (.dott, GeoBounds(south: 51.7022, west: 14.2745, north: 51.8076, east: 14.4092)),
        (.dott, GeoBounds(south: 49.8267, west: 8.5998, north: 49.9149, east: 8.7069)),
        (.dott, GeoBounds(south: 51.9022, west: 8.8056, north: 51.9745, east: 8.9365)),
        (.dott, GeoBounds(south: 51.4692, west: 7.3943, north: 51.5505, east: 7.5419)),
        (.dott, GeoBounds(south: 51.3686, west: 6.6664, north: 51.4531, east: 6.8151)),
        (.dott, GeoBounds(south: 51.1371, west: 6.6843, north: 51.294, east: 6.8991)),
        (.dott, GeoBounds(south: 50.9424, west: 10.9747, north: 51.0284, east: 11.1023)),
        (.dott, GeoBounds(south: 49.525, west: 10.9281, north: 49.6293, east: 11.0697)),
        (.dott, GeoBounds(south: 51.4073, west: 6.915, north: 51.5455, east: 7.1088)),
        (.dott, GeoBounds(south: 54.7392, west: 9.3528, north: 54.8439, east: 9.5133)),
        (.dott, GeoBounds(south: 47.6253, west: 9.3768, north: 47.7256, east: 9.539)),
        (.dott, GeoBounds(south: 50.82, west: 12.0332, north: 50.9204, east: 12.1157)),
        (.dott, GeoBounds(south: 52.4397, west: 10.4923, north: 52.5252, east: 10.5919)),
        (.dott, GeoBounds(south: 51.5246, west: 6.9472, north: 51.6108, east: 7.0437)),
        (.dott, GeoBounds(south: 53.4145, west: 9.7802, north: 53.6967, east: 10.2789)),
        (.dott, GeoBounds(south: 51.6387, west: 7.7086, north: 51.7344, east: 7.9014)),
        (.dott, GeoBounds(south: 52.26, west: 9.5647, north: 52.5007, east: 9.893)),
        (.dott, GeoBounds(south: 49.3288, west: 8.6176, north: 49.4539, east: 8.7379)),
        (.dott, GeoBounds(south: 49.0791, west: 9.0868, north: 49.2308, east: 9.3189)),
        (.dott, GeoBounds(south: 50.7444, west: 7.2321, north: 50.8025, east: 7.3398)),
        (.dott, GeoBounds(south: 52.0614, west: 8.5998, north: 52.1544, east: 8.7344)),
        (.dott, GeoBounds(south: 51.4973, west: 7.1339, north: 51.5797, east: 7.2834)),
        (.dott, GeoBounds(south: 51.5614, west: 7.1018, north: 51.642, east: 7.1775)),
        (.dott, GeoBounds(south: 51.1271, west: 6.8804, north: 51.2036, east: 7.0022)),
        (.dott, GeoBounds(south: 52.096, west: 9.8853, north: 52.197, east: 10.0174)),
        (.dott, GeoBounds(south: 48.6917, west: 11.3234, north: 48.833, east: 11.5982)),
        (.dott, GeoBounds(south: 50.8632, west: 11.543, north: 50.9672, east: 11.6482)),
        (.dott, GeoBounds(south: 49.3892, west: 7.6348, north: 49.4986, east: 7.8377)),
        (.dott, GeoBounds(south: 48.9649, west: 8.2776, north: 49.059, east: 8.5008)),
        (.dott, GeoBounds(south: 51.2454, west: 9.336, north: 51.3692, east: 9.5851)),
        (.dott, GeoBounds(south: 54.2734, west: 10.0288, north: 54.383, east: 10.2072)),
        (.dott, GeoBounds(south: 51.0544, west: 6.8995, north: 51.1576, east: 7.0137)),
        (.dott, GeoBounds(south: 51.2569, west: 12.2412, north: 51.4182, east: 12.5247)),
        (.dott, GeoBounds(south: 47.5243, west: 9.6391, north: 47.6092, east: 9.7528)),
        (.dott, GeoBounds(south: 53.8068, west: 10.5825, north: 53.9928, east: 10.8994)),
        (.dott, GeoBounds(south: 48.8617, west: 9.1264, north: 48.9381, east: 9.2885)),
        (.dott, GeoBounds(south: 49.4082, west: 8.3311, north: 49.569, east: 8.589)),
        (.dott, GeoBounds(south: 52.2501, west: 8.8456, north: 52.3304, east: 8.9823)),
        (.dott, GeoBounds(south: 51.1064, west: 6.3634, north: 51.2439, east: 6.4988)),
        (.dott, GeoBounds(south: 51.0519, west: 6.8618, north: 51.1432, east: 6.9314)),
        (.dott, GeoBounds(south: 51.3913, west: 6.7848, north: 51.5768, east: 6.9454)),
        (.dott, GeoBounds(south: 48.0524, west: 11.3135, north: 48.3714, east: 11.7866)),
        (.dott, GeoBounds(south: 51.8732, west: 7.538, north: 52.023, east: 7.7053)),
        (.dott, GeoBounds(south: 54.0269, west: 9.922, north: 54.1564, east: 10.0373)),
        (.dott, GeoBounds(south: 51.1397, west: 6.6118, north: 51.2502, east: 6.7563)),
        (.dott, GeoBounds(south: 49.3802, west: 10.934, north: 49.5102, east: 11.1618)),
        (.dott, GeoBounds(south: 52.2304, west: 7.9693, north: 52.3258, east: 8.1174)),
        (.dott, GeoBounds(south: 51.6802, west: 8.693, north: 51.7754, east: 8.8261)),
        (.dott, GeoBounds(south: 52.2846, west: 10.1457, north: 52.3715, east: 10.3028)),
        (.dott, GeoBounds(south: 52.3368, west: 12.9564, north: 52.4514, east: 13.1474)),
        (.dott, GeoBounds(south: 51.544, west: 7.1475, north: 51.6464, east: 7.2986)),
        (.dott, GeoBounds(south: 48.9671, west: 12.0227, north: 49.0506, east: 12.1659)),
        (.dott, GeoBounds(south: 48.4312, west: 9.1335, north: 48.5396, east: 9.2596)),
        (.dott, GeoBounds(south: 51.7905, west: 8.2427, north: 51.8802, east: 8.3831)),
        (.dott, GeoBounds(south: 52.238, west: 7.3664, north: 52.3354, east: 7.5334)),
        (.dott, GeoBounds(south: 54.0489, west: 12.0106, north: 54.1971, east: 12.1967)),
        (.dott, GeoBounds(south: 49.9421, west: 8.3689, north: 50.0197, east: 8.4781)),
        (.dott, GeoBounds(south: 49.1602, west: 6.871, north: 49.31, east: 7.0888)),
        (.dott, GeoBounds(south: 52.0187, west: 10.2662, north: 52.1909, east: 10.4147)),
        (.dott, GeoBounds(south: 50.7374, west: 7.1182, north: 50.8283, east: 7.2951)),
        (.dott, GeoBounds(south: 51.1193, west: 6.9723, north: 51.2317, east: 7.1405)),
        (.dott, GeoBounds(south: 48.6983, west: 9.0659, north: 48.8556, east: 9.2723)),
        (.dott, GeoBounds(south: 50.7571, west: 7.0678, north: 50.8597, east: 7.2034)),
        (.dott, GeoBounds(south: 48.4824, west: 9.0088, north: 48.5647, east: 9.1103)),
        (.dott, GeoBounds(south: 47.7349, west: 9.1186, north: 47.7957, east: 9.2181)),
        (.dott, GeoBounds(south: 48.3279, west: 9.9057, north: 48.4615, east: 10.0918)),
        (.dott, GeoBounds(south: 49.9273, west: 8.0728, north: 50.1206, east: 8.3414)),
        (.dott, GeoBounds(south: 52.3522, west: 10.6624, north: 52.4808, east: 10.882)),
        (.dott, GeoBounds(south: 50.6888, west: 12.4389, north: 50.7562, east: 12.537)),
        (.hopp, GeoBounds(south: 47.64, west: 9.1, north: 47.74, east: 9.25)),
        (.lime, GeoBounds(south: 48.6983, west: 9.0659, north: 48.8556, east: 9.2723)),
        (.lime, GeoBounds(south: 47.64, west: 9.1, north: 47.74, east: 9.25)),
        (.lime, GeoBounds(south: 49.9311, west: 8.4319, north: 50.2246, east: 8.7884)),
        (.lime, GeoBounds(south: 51.2053, west: 7.0316, north: 51.314, east: 7.2833)),
        (.voi, GeoBounds(south: 48.9649, west: 8.2776, north: 49.059, east: 8.5008)),
        (.voi, GeoBounds(south: 48.83, west: 8.59, north: 48.96, east: 8.81)),
        (.voi, GeoBounds(south: 49.4082, west: 8.3311, north: 49.569, east: 8.589)),
        (.voi, GeoBounds(south: 48.6983, west: 9.0659, north: 48.8556, east: 9.2723)),
        (.voi, GeoBounds(south: 48.4824, west: 9.0088, north: 48.5647, east: 9.1103)),
        (.voi, GeoBounds(south: 48.4312, west: 9.1335, north: 48.5396, east: 9.2596)),
        (.bird, GeoBounds(south: 41.6884, west: 12.2183, north: 42.0928, east: 12.7268)),
    ]

    static func providers(in viewport: GeoBounds) -> [ScooterProvider] {
        var available = Set<ScooterProvider>()
        if swissAreas.contains(where: { $0.intersects(viewport) }) {
            available.formUnion(ScooterProvider.allCases.filter { $0 != .pony })
        }
        for (provider, bounds) in regionalSystems where bounds.intersects(viewport) {
            available.insert(provider)
        }
        return ScooterProvider.allCases.filter { available.contains($0) }
    }
}
