// Generated by scripts/generate-api-contract.mjs from data/scooter-api.schema.json.
// Do not edit directly.

import Foundation

enum ScooterFeedSourceStatusPayload: String, Decodable, Sendable {
    case fresh = "fresh"
    case stale = "stale"
    case partial = "partial"
    case failed = "failed"
    case skipped = "skipped"
}

enum ScooterResponseModePayload: String, Decodable, Sendable {
    case vehicles = "vehicles"
    case clusters = "clusters"
}

struct ScooterVehiclePayload: Decodable, Sendable {
    let provider: String
    let latitude: Double
    let longitude: Double
    let battery: Int?
    let rangeMeters: Int?
    let vehicleID: String?
    let deepLink: String?
    let distanceMeters: Double?

    private enum CodingKeys: String, CodingKey {
        case provider
        case latitude = "lat"
        case longitude = "lng"
        case battery
        case rangeMeters = "range_m"
        case vehicleID = "vehicle_id"
        case deepLink = "deep_link"
        case distanceMeters = "distance_m"
    }
}

struct ScooterClusterPayload: Decodable, Sendable {
    let id: String
    let latitude: Double
    let longitude: Double
    let count: Int
    let providers: [String: Int]

    private enum CodingKeys: String, CodingKey {
        case id
        case latitude = "lat"
        case longitude = "lng"
        case count
        case providers
    }
}

struct ScooterResponseMetadataPayload: Decodable, Sendable {
    let partial: Bool
    let stale: Bool
    let failedSources: [String]
    let sources: [String: ScooterFeedSourceStatusPayload]
    let generatedAt: String
    let truncated: Bool
    let totalVehicles: Int
    let mode: ScooterResponseModePayload
    let zoom: Int?
}

struct ScooterAPIResponsePayload: Decodable, Sendable {
    let vehicles: [ScooterVehiclePayload]
    let clusters: [ScooterClusterPayload]
    let providers: [String: Int]
    let meta: ScooterResponseMetadataPayload
}
